export const posts = [
  {
    slug: 'reussir-strategie-marketing-digital',
    category: 'Marketing Digital',
    title: '5 conseils pour réussir votre stratégie marketing digital',
    excerpt: "Avant de lancer des campagnes, il faut clarifier ses objectifs, connaître son audience et choisir les bons canaux. Voici les fondamentaux à ne pas négliger.",
    readTime: '5 min de lecture',
    image: '/images/formation-marketing.jpg',
  },
  {
    slug: 'engager-audience-community-management',
    category: 'Community Management',
    title: "Community management : comment engager durablement votre audience",
    excerpt: "Un calendrier éditorial cohérent, des formats variés et une vraie écoute de la communauté : les clés d'une présence social media qui convertit.",
    readTime: '5 min de lecture',
    image: '/images/portfolio-kemaf.jpg',
  },
  {
    slug: 'identite-visuelle-marque-forte',
    category: 'Graphisme & Design',
    title: 'Pourquoi une identité visuelle forte change tout pour votre marque',
    excerpt: "Logo, charte graphique, ton éditorial : une identité cohérente crédibilise votre marque et la rend immédiatement reconnaissable.",
    readTime: '5 min de lecture',
    image: '/images/formation-graphisme.jpg',
  },
  {
    slug: 'video-format-qui-capte-attention',
    category: 'Production Vidéo',
    title: 'Vidéo : le format qui capte le plus l’attention en 2026',
    excerpt: "Reels, spots publicitaires, aftermovies : la vidéo reste le levier le plus engageant. Voici comment l'intégrer efficacement à votre stratégie.",
    readTime: '5 min de lecture',
    image: '/images/portfolio-spottv.jpg',
  },
  {
    slug: 'site-web-qui-convertit',
    category: 'Développement Web',
    title: 'Les fondamentaux d’un site web qui convertit vraiment',
    excerpt: "Vitesse, clarté du message, appels à l'action visibles : les leviers concrets pour transformer vos visiteurs en clients.",
    readTime: '5 min de lecture',
    image: '/images/portfolio-cotonou.jpg',
  },
  {
    slug: 'construire-strategie-digitale-sur-mesure',
    category: 'Stratégie & Conseil',
    title: 'Comment construire une stratégie digitale vraiment sur mesure',
    excerpt: "Chaque marque a ses propres objectifs. Un audit digital honnête est le point de départ de toute stratégie efficace.",
    readTime: '5 min de lecture',
    image: '/images/formations-hero.jpg',
  },
];
