// Auto-généré à partir de public/images/Projet — ne pas éditer à la main.
export const portfolioProjects = [
  {
    id: 'cao',
    title: 'CAO Consulting',
    category: 'Design',
    client: 'CAO Consulting',
    location: 'Bénin · Gabon',
    tags: ['Identité visuelle', 'Cartes de visite', 'Community Management'],
    description:
      "Accompagnement complet de ce cabinet de conseil stratégique : identité de marque, supports imprimés (cartes de visite, packaging) et animation des réseaux sociaux.",
    gallery: [
      '/images/portfolio/cao/001-24-juillet-2026.png',
      '/images/portfolio/cao/002-aml-10-ao-ut-cao.png',
      '/images/portfolio/cao/003-aml-12-ao-ut-conseil-strategique-performance-5.png',
      '/images/portfolio/cao/004-aml-jeudi-01-juillet-cao-aml.png',
      '/images/portfolio/cao/005-aml-lundi-13-juil-ca0.png',
      '/images/portfolio/cao/006-aml-mer-15-juil-ca0.png',
      '/images/portfolio/cao/007-aml-partenaires-cao-aml.png',
      '/images/portfolio/cao/008-aml-partenaires-cao-aml.png',
      '/images/portfolio/cao/009-aml-ven-17-juil-ca0.png',
      '/images/portfolio/cao/010-aml-week-end-cao.png',
      '/images/portfolio/cao/011-carte-de-visite-mockup-carte-de-visite-1.png',
      '/images/portfolio/cao/012-carte-de-visite-mockup-carte-de-visite-2.png',
      '/images/portfolio/cao/013-carte-de-visite-mockup-carte-de-visite-3.png',
      '/images/portfolio/cao/014-carte-de-visite-resto-vf.png',
      '/images/portfolio/cao/015-carte-de-visite-resto.png',
      '/images/portfolio/cao/016-carte-de-visite-verso-1-vf.png',
      '/images/portfolio/cao/017-carte-de-visite-verso-1.png',
      '/images/portfolio/cao/018-carte-de-visite-verso-2-vf.png',
      '/images/portfolio/cao/019-carte-de-visite-verso-2.png',
      '/images/portfolio/cao/020-jeudi-01-juillet-cao.png',
      '/images/portfolio/cao/021-logo-1.png',
      '/images/portfolio/cao/022-logo-frame-127.svg',
      '/images/portfolio/cao/023-logo-logo-1.png',
      '/images/portfolio/cao/024-logo-logo-2.png',
      '/images/portfolio/cao/025-logo-logo-fond-transparent.png',
      '/images/portfolio/cao/026-logo-logo-fond-transparent.svg',
      '/images/portfolio/cao/027-lundi-matin-cao.png',
      '/images/portfolio/cao/028-lundi-matin.png',
      '/images/portfolio/cao/029-mardi-30-juin-cao.png',
      '/images/portfolio/cao/030-mercredi-31-juin-cao.png',
      '/images/portfolio/cao/031-mockup-1.png',
      '/images/portfolio/cao/032-mockup-10.png',
      '/images/portfolio/cao/033-mockup-11.png',
      '/images/portfolio/cao/034-mockup-12.png',
      '/images/portfolio/cao/035-mockup-13.png',
      '/images/portfolio/cao/036-mockup-2.png',
      '/images/portfolio/cao/037-mockup-3.png',
      '/images/portfolio/cao/038-mockup-4.png',
      '/images/portfolio/cao/039-mockup-5.png',
      '/images/portfolio/cao/040-mockup-6.png',
      '/images/portfolio/cao/041-mockup-7.png',
      '/images/portfolio/cao/042-mockup-8.png',
      '/images/portfolio/cao/043-mockup-9.png',
      '/images/portfolio/cao/044-partenaires-cao.png',
      '/images/portfolio/cao/045-cao.svg',
      '/images/portfolio/cao/046-image-8.png'
    ],
  },
  {
    id: 'fss',
    title: 'Freedom and Serenity Solutions',
    category: 'Campagne',
    client: 'Freedom and Serenity Solutions',
    location: 'États-Unis',
    tags: ['Community Management', 'Design graphique'],
    description:
      "Création de contenus et animation des réseaux sociaux pour ce cabinet de conseil en prévoyance et assurance-vie basé aux États-Unis.",
    gallery: [
      '/images/portfolio/fss/001-01-juillet-fss.png',
      '/images/portfolio/fss/002-01-juin-fss.png',
      '/images/portfolio/fss/003-02-juillet-fss.png',
      '/images/portfolio/fss/004-02-juin-fss.png',
      '/images/portfolio/fss/005-03-juin-fss.png',
      '/images/portfolio/fss/006-03juillet-fss.png',
      '/images/portfolio/fss/007-04-juin-fss.png',
      '/images/portfolio/fss/008-04-juillet-fss.png',
      '/images/portfolio/fss/009-05-juin-fss.png',
      '/images/portfolio/fss/010-06-mai-fss.png',
      '/images/portfolio/fss/011-07-mai-fss-revue.png',
      '/images/portfolio/fss/012-07-mai-fss.png',
      '/images/portfolio/fss/013-08-juin-fss.png',
      '/images/portfolio/fss/014-08-mai-fss-revue.png',
      '/images/portfolio/fss/015-08-mai-fss.png',
      '/images/portfolio/fss/016-09-juin-fss-version-francaise.png',
      '/images/portfolio/fss/017-09-juin-fss.png',
      '/images/portfolio/fss/018-10-juin-fss.png',
      '/images/portfolio/fss/019-11-juin-fss.png',
      '/images/portfolio/fss/020-11-mai-fss.png',
      '/images/portfolio/fss/021-12-juin-fss.png',
      '/images/portfolio/fss/022-12-mai-fss-new.png',
      '/images/portfolio/fss/023-12-mai-fss.png',
      '/images/portfolio/fss/024-13-mai-fss.png',
      '/images/portfolio/fss/025-14-mai-fss.png',
      '/images/portfolio/fss/026-15-juin-fss-aml.png',
      '/images/portfolio/fss/027-15-juin-fss.png',
      '/images/portfolio/fss/028-15-mai-fss-revue-v1-1.png',
      '/images/portfolio/fss/029-15-mai-fss-revue-v1.png',
      '/images/portfolio/fss/030-15-mai-fss-revue.png',
      '/images/portfolio/fss/031-16-juin-fss.png',
      '/images/portfolio/fss/032-17-juin-fss.png',
      '/images/portfolio/fss/033-18-juin-fss.png',
      '/images/portfolio/fss/034-18-mai-fss-v1.png',
      '/images/portfolio/fss/035-18-mai-fss.png',
      '/images/portfolio/fss/036-19-mai-fss-v1.png',
      '/images/portfolio/fss/037-19-mai-fss-v2.png',
      '/images/portfolio/fss/038-19-mai-fss-v3.png',
      '/images/portfolio/fss/039-20-mai-fss-v1.png',
      '/images/portfolio/fss/040-21-mai-fss-v1.png',
      '/images/portfolio/fss/041-22-juin-fss.png',
      '/images/portfolio/fss/042-22-mai-fss-v1.png',
      '/images/portfolio/fss/043-23-juin-fss.png',
      '/images/portfolio/fss/044-24-juin-fss.png',
      '/images/portfolio/fss/045-25-juin-fss.png',
      '/images/portfolio/fss/046-25-mai-fss.png',
      '/images/portfolio/fss/047-25-mai-fss-ang.png',
      '/images/portfolio/fss/048-26-juin-fss.png',
      '/images/portfolio/fss/049-26-mai-fss-v1.png',
      '/images/portfolio/fss/050-26-mai-fss.png',
      '/images/portfolio/fss/051-27-mai-fss.png',
      '/images/portfolio/fss/052-28-mai.png',
      '/images/portfolio/fss/053-29-juin-fss.png',
      '/images/portfolio/fss/054-29-mai-fss.png',
      '/images/portfolio/fss/055-30-juin-fss.png',
      '/images/portfolio/fss/056-frame-122.svg',
      '/images/portfolio/fss/057-licence-fss-version-francaise.png',
      '/images/portfolio/fss/058-licence-version-anglaise-aml-h.png',
      '/images/portfolio/fss/059-licence-version-anglaise-aml.png',
      '/images/portfolio/fss/060-licence-version-francaise-aml.png',
      '/images/portfolio/fss/061-tabaski-fss.png',
      '/images/portfolio/fss/062-version-francaise.png',
      '/images/portfolio/fss/063-image-48.png'
    ],
  },
  {
    id: 'tca',
    title: 'Travel Consulting Agency',
    category: 'Campagne',
    client: 'Travel Consulting Agency',
    location: 'Cotonou, Bénin',
    tags: ['Community Management', 'Design graphique'],
    description:
      "Stratégie de contenu et animation des réseaux sociaux pour cette agence spécialisée dans l'accompagnement aux démarches de voyage et de visa.",
    gallery: [
      '/images/portfolio/tca/001-01-ao-ut-tca.png',
      '/images/portfolio/tca/002-01-juin-tca-new.png',
      '/images/portfolio/tca/003-01-juillet-2026.png',
      '/images/portfolio/tca/004-02-juin-tca.png',
      '/images/portfolio/tca/005-02-juillet-2026.png',
      '/images/portfolio/tca/006-03-ao-ut-tca.png',
      '/images/portfolio/tca/007-03-juillet-2026.png',
      '/images/portfolio/tca/008-04-ao-ut-tca.png',
      '/images/portfolio/tca/009-04-juin-tca.png',
      '/images/portfolio/tca/010-05-ao-ut-tca.png',
      '/images/portfolio/tca/011-05-juin-tca.png',
      '/images/portfolio/tca/012-058f2dcf-d146-4e0a-b99e-ffae1059a92c.png',
      '/images/portfolio/tca/013-06-ao-ut-tca.png',
      '/images/portfolio/tca/014-06-juillet-2026.png',
      '/images/portfolio/tca/015-07-ao-ut-tca.png',
      '/images/portfolio/tca/016-08-juin-tca.png',
      '/images/portfolio/tca/017-09-juin-tca.png',
      '/images/portfolio/tca/018-10-juin-tca.png',
      '/images/portfolio/tca/019-11-ao-ut-tca.png',
      '/images/portfolio/tca/020-11-juin-tca.png',
      '/images/portfolio/tca/021-11-mai-tca.png',
      '/images/portfolio/tca/022-12-juin-tca.png',
      '/images/portfolio/tca/023-12-mai-tca.png',
      '/images/portfolio/tca/024-13-juillet-tca.png',
      '/images/portfolio/tca/025-13-mai-tca.png',
      '/images/portfolio/tca/026-14-ao-ut-tca.png',
      '/images/portfolio/tca/027-14-mai-tca.png',
      '/images/portfolio/tca/028-15-juin-tca.png',
      '/images/portfolio/tca/029-15-mai-tca.png',
      '/images/portfolio/tca/030-16-juin-tca.png',
      '/images/portfolio/tca/031-17-juin-tca.png',
      '/images/portfolio/tca/032-18-ao-ut-tca.png',
      '/images/portfolio/tca/033-18-juin-tca.png',
      '/images/portfolio/tca/034-18-mai-tca.png',
      '/images/portfolio/tca/035-19-ao-ut-tca.png',
      '/images/portfolio/tca/036-19-juin-tca.png',
      '/images/portfolio/tca/037-19-mai-tca.png',
      '/images/portfolio/tca/038-20-ao-ut-tca.png',
      '/images/portfolio/tca/039-20-mai-tca.png',
      '/images/portfolio/tca/040-21-juillet-tca.png',
      '/images/portfolio/tca/041-21-mai-tca-v1.png',
      '/images/portfolio/tca/042-21-mai-tca.png',
      '/images/portfolio/tca/043-22-juillet-tca.png',
      '/images/portfolio/tca/044-22-juin-tca.png',
      '/images/portfolio/tca/045-22-mai-tca-v1.png',
      '/images/portfolio/tca/046-22-mai-tca.png',
      '/images/portfolio/tca/047-23-juillet-tca.png',
      '/images/portfolio/tca/048-23-juin-tca.png',
      '/images/portfolio/tca/049-24-juillet-tca.png',
      '/images/portfolio/tca/050-24-juin-tca.png',
      '/images/portfolio/tca/051-25-juin-tca.png',
      '/images/portfolio/tca/052-25-mai-tca-v1.png',
      '/images/portfolio/tca/053-26-juin-tca.png',
      '/images/portfolio/tca/054-26-mai-tca.png',
      '/images/portfolio/tca/055-27-juillet-tca.png',
      '/images/portfolio/tca/056-28-juillet-tca.png',
      '/images/portfolio/tca/057-28-mai-tca-aml.png',
      '/images/portfolio/tca/058-28-mai-tca-aml1.png',
      '/images/portfolio/tca/059-28-mai-tca.png',
      '/images/portfolio/tca/060-29-juillet-tca.png',
      '/images/portfolio/tca/061-29-juin-tca.png',
      '/images/portfolio/tca/062-29-mai-tca.png',
      '/images/portfolio/tca/063-30-juillet-tca.png',
      '/images/portfolio/tca/064-30-juin-tca.png',
      '/images/portfolio/tca/065-31-juillet-tca.png',
      '/images/portfolio/tca/066-4-mai.png',
      '/images/portfolio/tca/067-5-mai.png',
      '/images/portfolio/tca/068-6-mai.png',
      '/images/portfolio/tca/069-7-mai.png',
      '/images/portfolio/tca/070-8-mai.png',
      '/images/portfolio/tca/071-ascension-v1.png',
      '/images/portfolio/tca/072-avi-tca.png',
      '/images/portfolio/tca/073-frame-123.png',
      '/images/portfolio/tca/074-lundi-17-ao-ut-tca.png',
      '/images/portfolio/tca/075-new-lundi.png',
      '/images/portfolio/tca/076-promo-15-tca-v1.png',
      '/images/portfolio/tca/077-promo-15-tca.png',
      '/images/portfolio/tca/078-pentec-ote-tca.png',
      '/images/portfolio/tca/079-tabaski-tca.png',
      '/images/portfolio/tca/080-today.png',
      '/images/portfolio/tca/081-magic-edit-tufisvbsmhn3otgjmsmxoda0m2jjogi2ywuzmwu2otywndk5mzi5ywq0yzu3mim2mjqji1rsqu5trk9stufusu9ox1jfuvvfu1q-1.png'
    ],
  },
];

export const portfolioCategories = ['Tout', 'Design', 'Campagne'];
